services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - postgres-db
      - redis-db

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-db:
    image: redis:alpine

volumes:
  postgres-data: